### ISSUE TITLE
Plugin stuck on "Ready-to-install package ... Just run your package manager install command."

### ISSUE THREAD

**Issue by paul-uz** [mskelton/vscode-npm-outdated#20]
The plugin correctly detects out dated versions, and updates the number when I click to do so. It then prompts with a message like:

> Ready-to-install package "@types/aws-lambda" at version 8.10.114. Just run your package manager install command.

So, I run `npm i` and the update is installed. However, the plugin continues to persist the "Ready-to-install" message.

I'm using v2.2.0 and VS Code 1.76.2 on MacOS 11.6.5

**Comment by rentalhost** [comment]
Thanks for reporting.

I have three questions:

1. What is displayed to console when you click on "do it for me" button? Or maybe you are running `npm i` directly?

2. Are you using in fact `npm i` or other package manager? Your project contains `yarn.lock` or `pnpm-lock.yml` files?

3. When you reload vscode it is fixed or the message of "ready to install" still exists?

Thanks!

**Comment by paul-uz** [comment]
1. Yes, I'm running `npm i` myself. I don't see a "do it for me" button
2. 2. Yes, using `npm`
3. Reloading VSCode doesn't fix the issue. I even reinstalled the extension, same issue

Oddly, it seems to work, a bit. See screenshot below. Moment is flagged OK, but util-dynamodb is still saying to un the install command, even though I have.

<img width="1173" alt="Screenshot 2023-03-24 at 09 22 27" src="https://user-images.githubusercontent.com/73826774/227478505-70944b7b-0eca-44ca-80fc-90af3882e502.png">

**Comment by rentalhost** [comment]
Would it be feasible for you to delete the "node_modules" folder and run "npm i" again? I suspect it's some defect within node_modules that may be causing problems (this usually happens after many updates to npm itself, or when using other package managers).

**Comment by backtoyoujames** [comment]
I too am experiencing this issue which seemed to appear pretty recently as one of the projects wasn't showing the ''now run your package manager." message but now it is that project and another one I just created.  There aren't any error indicators in the vscode output window so it's not clear what's going on.

I have updated vscode a few times so perhaps it's related?
VSCode Version: 1.78.1

**Comment by rentalhost** [comment]
@backtoyoujames I suspect this problem is related to the missing file `package-lock.json`, which would only be created after `npm install`. And since the file doesn't exist and the extension is watching this file for "modifications" (and not for "creation", too), it fails to update the diagnostics and it will always display "_now run your package manager_" (closing and opening _vscode_ should do the trick).

Another related issue is if you are using `pnpm` or `yarn`, which are currently not supported.

However, PR #22 should resolve the first case and add support for `pnpm`. `yarn` is not yet supported.

**Comment by paul-uz** [comment]
I'm still having this issue despite having a package-lock.json file and using npm.

**Comment by rentalhost** [comment]
@paul-uz Restarting vscode the problem persists? You can create a reduced case for I test?

**Comment by paul-uz** [comment]
> @paul-uz Restarting vscode the problem persists? You can create a reduced case for I test?

Yup restarted VSCode several times, same thing every time.

**Comment by rentalhost** [comment]
@paul-uz It's a little weird. Can you create a reduced project? Maybe only package.json could help to understand. But if you could generate a reduced project it would help more. So I can see if PR is the solution or even improve it.

**Comment by ImUrX** [comment]
I have this happen on npm workspaces!

**Comment by ImUrX** [comment]
The main package.json doesnt have this error but any inner package.json keeps saying this :p

**Comment by rentalhost** [comment]
> The main package.json doesnt have this error but any inner package.json keeps saying this :p

You have package.json in a non-root path? Maybe this need to be fixed, because I never do in that way. I will check in this week.

**Comment by paul-uz** [comment]
> > The main package.json doesnt have this error but any inner package.json keeps saying this :p
> 
> You have package.json in a non-root path? Maybe this need to be fixed, because I never do in that way. I will check in this week.

It's quite a common thing with a monorepo

**Comment by mmospanenko** [comment]
maybe we can turn it off?

**Comment by rentalhost** [comment]
Must be fixed now via #22.

**Comment by ImUrX** [comment]
but it still isnt merged :pensive:

**Comment by rentalhost** [comment]
Yeah, I just asked @mskelton if he will approves the PR.

**Comment by rentalhost** [comment]
I have published a fork extension called [npm-outdated-plus](https://marketplace.visualstudio.com/items?itemName=rentalhost.npm-outdated-plus) with this changes.
